name: tshirt_print
description: Create pixel art designs and order custom t-shirts.
publish_to: 'none'
version: 1.0.0+1  # Format: version_name+build_number

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  image: ^4.1.4
  cupertino_icons: ^1.0.6
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.6
  cloud_firestore: ^6.1.2
  cloud_functions: ^6.0.6
  flutter_stripe: ^12.2.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
